# Generated by Django 4.0 on 2021-12-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_class', models.CharField(max_length=225, verbose_name='буква класс')),
                ('class_number', models.IntegerField(verbose_name='Номер класса')),
            ],
        ),
        migrations.CreateModel(
            name='Lesssons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='название урока')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='ФИО')),
                ('parents_number', models.CharField(max_length=225, verbose_name='Номер родителей')),
                ('address', models.CharField(max_length=225, verbose_name='Адрес')),
                ('image_students', models.ImageField(upload_to='image/Pupils', verbose_name='Фото')),
                ('class_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.classes', verbose_name='класс')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='ФИО')),
                ('address', models.CharField(max_length=225, verbose_name='Адрес')),
                ('cell_number', models.CharField(max_length=225, verbose_name='Номер телефона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Zauchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/Zauchi')),
                ('cell_number', models.CharField(max_length=225, verbose_name='Номер телефона')),
            ],
        ),
        migrations.AlterField(
            model_name='director',
            name='cell_number',
            field=models.CharField(max_length=225, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.classes', verbose_name='классы')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.director', verbose_name='директор')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.lesssons', verbose_name='уроки')),
                ('pupils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.pupils', verbose_name='ученики')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.teachers', verbose_name='учителя')),
                ('zauchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.zauchi', verbose_name='завуч')),
            ],
        ),
        migrations.AddField(
            model_name='lesssons',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.teachers', verbose_name='классный руководитель'),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_school.teachers', verbose_name='классный руководитель'),
        ),
    ]
